name: clang-format check

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  formatting-check:
    name: clang-format check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Formatting Check (Source)
      uses: jidicula/clang-format-action@v4.18.0
      with:
        clang-format-version: '18'
        check-path: 'Source'

    - name: Formatting Check (test)
      uses: jidicula/clang-format-action@v4.18.0
      with:
        clang-format-version: '18'
        check-path: 'test'
